//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopGame.Client.Resources.Models.Incoming {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameForCreate_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameForCreate_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopGame.Client.Resources.Models.Incoming.GameForCreate.ru", typeof(GameForCreate_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоимость.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} должна иметь быть минимум {1},максимум {2}.
        /// </summary>
        internal static string CostError {
            get {
                return ResourceManager.GetString("CostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Стоимость должно быть заполнено.
        /// </summary>
        internal static string CostRequired {
            get {
                return ResourceManager.GetString("CostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} должно иметь максимум {1} символов.
        /// </summary>
        internal static string DescError {
            get {
                return ResourceManager.GetString("DescError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Описание должно быть заполнено.
        /// </summary>
        internal static string DescRequired {
            get {
                return ResourceManager.GetString("DescRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жанр.
        /// </summary>
        internal static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Жанр должно быть заполнено.
        /// </summary>
        internal static string GenreRequired {
            get {
                return ResourceManager.GetString("GenreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В наличии.
        /// </summary>
        internal static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {1} должно иметь минимум {0} символов.
        /// </summary>
        internal static string NameError {
            get {
                return ResourceManager.GetString("NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Название должно быть заполнено.
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Короткое описание.
        /// </summary>
        internal static string ShortDesc {
            get {
                return ResourceManager.GetString("ShortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле Короткое Описание должно быть заполнено.
        /// </summary>
        internal static string ShortDescRequired {
            get {
                return ResourceManager.GetString("ShortDescRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле {0} должно иметь максимум {1} символов.
        /// </summary>
        internal static string ShortError {
            get {
                return ResourceManager.GetString("ShortError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ссылка на картинку.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле ссылка на картинку должно быть заполнено.
        /// </summary>
        internal static string UrlRequired {
            get {
                return ResourceManager.GetString("UrlRequired", resourceCulture);
            }
        }
    }
}
